repos:
  - repo: "meta"
    hooks:
      - id: "check-hooks-apply"
      - id: "check-useless-excludes"

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "3e8a8703264a2f4a69428a0aa4dcb512790b2c8c"  # frozen: v6.0.0
    hooks:
      - id: "check-added-large-files"
      - id: "check-merge-conflict"
      - id: "check-yaml"

  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: "5e2fb545eba1ea9dc051f6f962d52fe8f76a9794"  # frozen: v0.15.13
    hooks:
      - id: "ruff"
        args: ["--fix"]

  - repo: "https://github.com/psf/black-pre-commit-mirror"
    rev: "30528d9894a7da387a9f8e236b65d90d0d6b54b5"  # frozen: 26.5.0
    hooks:
      - id: "black"
        language_version: "python3.11"
